# Generated by Django 5.1.1 on 2025-12-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Admin'), ('CONTENT_MANAGER', 'Content Manager'), ('SCHOOL_ADMIN', 'School Admin'), ('TEACHER', 'Teacher')], default='TEACHER', help_text='User role determines access permissions', max_length=20),
        ),
    ]
