# Generated by Django 5.1.1 on 2025-12-08 08:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_add_content_manager_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique configuration key (e.g., 'branding.logo_url')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Configuration value (stored as text, converted based on config_type)"
                    ),
                ),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("STRING", "String"),
                            ("INTEGER", "Integer"),
                            ("FLOAT", "Float"),
                            ("BOOLEAN", "Boolean"),
                            ("JSON", "JSON"),
                            ("URL", "URL"),
                            ("EMAIL", "Email"),
                            ("COLOR", "Color"),
                            ("FILE", "File Path"),
                        ],
                        default="STRING",
                        help_text="Data type for proper value conversion",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for admin interface",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this configuration controls",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="general",
                        help_text="Configuration category for organization",
                        max_length=50,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this config is accessible via public API",
                    ),
                ),
                (
                    "is_editable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this config can be edited via admin interface",
                    ),
                ),
                (
                    "validation_regex",
                    models.CharField(
                        blank=True,
                        help_text="Optional regex pattern for value validation",
                        max_length=500,
                    ),
                ),
                (
                    "min_value",
                    models.FloatField(
                        blank=True,
                        help_text="Minimum value for numeric types",
                        null=True,
                    ),
                ),
                (
                    "max_value",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum value for numeric types",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configurations",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ConfigChangeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField()),
                ("change_reason", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="config.systemconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration Change Log",
                "verbose_name_plural": "Configuration Change Logs",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique feature flag name (e.g., 'video_downloads_enabled')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable feature name", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of what this feature flag controls"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this feature is currently enabled",
                    ),
                ),
                (
                    "is_permanent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this flag can be toggled (false) or is permanent (true)",
                    ),
                ),
                (
                    "applies_to_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="If specified, flag only applies to these user roles",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applies_to_schools",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If specified, flag only applies to these schools",
                        to="accounts.school",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_feature_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_feature_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag",
                "verbose_name_plural": "Feature Flags",
                "ordering": ["display_name"],
                "indexes": [
                    models.Index(fields=["name"], name="config_feat_name_e79e3d_idx"),
                    models.Index(
                        fields=["is_enabled"], name="config_feat_is_enab_9b651c_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="systemconfig",
            index=models.Index(fields=["key"], name="config_syst_key_94aeee_idx"),
        ),
        migrations.AddIndex(
            model_name="systemconfig",
            index=models.Index(
                fields=["category", "name"], name="config_syst_categor_d253fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemconfig",
            index=models.Index(
                fields=["is_public"], name="config_syst_is_publ_84f030_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="configchangelog",
            index=models.Index(
                fields=["config", "changed_at"], name="config_conf_config__f87347_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="configchangelog",
            index=models.Index(
                fields=["changed_by", "changed_at"],
                name="config_conf_changed_2a8935_idx",
            ),
        ),
    ]
