# Generated by Django 5.1 on 2025-11-25 06:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether this playlist is visible to other teachers in the school')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for the share link', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shares', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='content.playlist')),
            ],
            options={
                'verbose_name': 'Playlist Share',
                'verbose_name_plural': 'Playlist Shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file_uri', models.URLField(help_text='Firebase Storage path for the resource file')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('doc', 'Word Document'), ('docx', 'Word Document (DOCX)'), ('ppt', 'PowerPoint'), ('pptx', 'PowerPoint (PPTX)'), ('xls', 'Excel Spreadsheet'), ('xlsx', 'Excel Spreadsheet (XLSX)'), ('txt', 'Text File'), ('image', 'Image File'), ('other', 'Other')], help_text='Type of resource file', max_length=10)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('grade', models.CharField(blank=True, choices=[('K', 'Kindergarten'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8')], help_text='Target grade level (optional)', max_length=2)),
                ('topic', models.CharField(blank=True, choices=[('fractions_basics', 'Fractions Basics'), ('equivalent_fractions', 'Equivalent Fractions'), ('comparing_ordering', 'Comparing/Ordering'), ('number_line', 'Number Line'), ('mixed_improper', 'Mixed ↔ Improper'), ('add_subtract_fractions', 'Add/Subtract Fractions'), ('multiply_divide_fractions', 'Multiply/Divide Fractions (6+)'), ('decimals_percents', 'Decimals & Percents'), ('ratio_proportion', 'Ratio/Proportion (6+)'), ('word_problems', 'Word Problems')], help_text='Related topic (optional)', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Additional tags for categorization')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('download_completed', models.BooleanField(default=True, help_text='Whether the download was completed successfully')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_downloads', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='content.resource')),
            ],
            options={
                'verbose_name': 'Asset Download',
                'verbose_name_plural': 'Asset Downloads',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the video content')),
                ('grade', models.CharField(choices=[('K', 'Kindergarten'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8')], help_text='Target grade level for this content', max_length=2)),
                ('topic', models.CharField(choices=[('fractions_basics', 'Fractions Basics'), ('equivalent_fractions', 'Equivalent Fractions'), ('comparing_ordering', 'Comparing/Ordering'), ('number_line', 'Number Line'), ('mixed_improper', 'Mixed ↔ Improper'), ('add_subtract_fractions', 'Add/Subtract Fractions'), ('multiply_divide_fractions', 'Multiply/Divide Fractions (6+)'), ('decimals_percents', 'Decimals & Percents'), ('ratio_proportion', 'Ratio/Proportion (6+)'), ('word_problems', 'Word Problems')], help_text='Primary topic covered in this video', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Additional tags for categorization (JSON array)')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Video duration in seconds', null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('storage_uri', models.URLField(help_text='Firebase Storage path for the video file')),
                ('thumbnail_uri', models.URLField(blank=True, help_text='Firebase Storage path for video thumbnail')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Current status in the approval workflow', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When this video was submitted for review', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When this video was reviewed', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the reviewer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who uploaded this video', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_videos', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(help_text='School this video belongs to', on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
            ],
            options={
                'verbose_name': 'Video Asset',
                'verbose_name_plural': 'Video Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(help_text='Position in the playlist (1-based)')),
                ('notes', models.TextField(blank=True, help_text="Teacher's notes about this video in the context of the playlist")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.playlist')),
                ('video_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.videoasset')),
            ],
            options={
                'verbose_name': 'Playlist Item',
                'verbose_name_plural': 'Playlist Items',
                'ordering': ['playlist', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DailyAssetStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('unique_viewers', models.PositiveIntegerField(default=0)),
                ('total_watch_time', models.PositiveIntegerField(default=0, help_text='Total seconds watched across all views')),
                ('avg_completion_rate', models.FloatField(blank=True, help_text='Average completion percentage (0.0-1.0)', null=True)),
                ('playlist_adds', models.PositiveIntegerField(default=0, help_text='Times this video was added to playlists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='content.videoasset')),
            ],
            options={
                'verbose_name': 'Daily Asset Stats',
                'verbose_name_plural': 'Daily Asset Stats',
                'ordering': ['-date', 'asset'],
            },
        ),
        migrations.CreateModel(
            name='AssetView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Browser session ID to avoid duplicate counting', max_length=50)),
                ('duration_watched', models.PositiveIntegerField(blank=True, help_text='Seconds of video watched (if available)', null=True)),
                ('completion_percentage', models.FloatField(blank=True, help_text='Percentage of video completed (0.0-1.0)', null=True)),
                ('referrer', models.URLField(blank=True, help_text='Page that linked to this video')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_views', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='content.videoasset')),
            ],
            options={
                'verbose_name': 'Asset View',
                'verbose_name_plural': 'Asset Views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('PLAYLIST_SHARED', 'Playlist Shared'), ('PLAYLIST_DUPLICATED', 'Playlist Duplicated'), ('RESOURCE_DOWNLOADED', 'Resource Downloaded'), ('VIDEO_VIEWED', 'Video Viewed'), ('USER_LOGIN', 'User Login'), ('CONTENT_UPLOADED', 'Content Uploaded'), ('CONTENT_APPROVED', 'Content Approved'), ('CONTENT_REJECTED', 'Content Rejected')], db_index=True, max_length=50)),
                ('metadata', models.JSONField(default=dict, help_text='Additional data about the action (original_owner, playlist_id, etc.)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='content_aud_action_637e70_idx'), models.Index(fields=['user', 'created_at'], name='content_aud_user_id_9644f1_idx'), models.Index(fields=['created_at'], name='content_aud_created_2eb55f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['school', 'is_public'], name='content_pla_school__95684f_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['owner', 'created_at'], name='content_pla_owner_i_b98216_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistshare',
            index=models.Index(fields=['share_token'], name='content_pla_share_t_9e5587_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistshare',
            index=models.Index(fields=['playlist', 'is_active'], name='content_pla_playlis_e2ddee_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistshare',
            index=models.Index(fields=['created_by', 'created_at'], name='content_pla_created_a8006c_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['school', 'status'], name='content_res_school__3693bf_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['file_type', 'status'], name='content_res_file_ty_19444f_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['owner', 'created_at'], name='content_res_owner_i_540d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['school', 'status', 'file_type'], name='content_res_school__9d0d73_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['school', 'status', 'created_at'], name='content_res_school__832f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['title'], name='content_res_title_7d583c_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['grade', 'topic'], name='content_res_grade_3cf284_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdownload',
            index=models.Index(fields=['resource', 'downloaded_at'], name='content_ass_resourc_1b03c4_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdownload',
            index=models.Index(fields=['user', 'downloaded_at'], name='content_ass_user_id_2a09a8_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdownload',
            index=models.Index(fields=['downloaded_at'], name='content_ass_downloa_bb79a5_idx'),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['school', 'status'], name='content_vid_school__b3ae99_idx'),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['grade', 'topic'], name='content_vid_grade_e876b9_idx'),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['owner', 'created_at'], name='content_vid_owner_i_d77129_idx'),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['status', 'created_at'], name='content_vid_status_5cb0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['school', 'status', 'grade'], name='content_vid_school__c00c36_idx'),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['school', 'status', 'topic'], name='content_vid_school__95ae8d_idx'),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['school', 'status', 'created_at'], name='content_vid_school__c9f850_idx'),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['title'], name='content_vid_title_9bba0b_idx'),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['school', 'grade', 'topic', 'status'], name='content_vid_school__571253_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistitem',
            index=models.Index(fields=['playlist', 'order'], name='content_pla_playlis_06d1af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistitem',
            unique_together={('playlist', 'order')},
        ),
        migrations.AddIndex(
            model_name='dailyassetstats',
            index=models.Index(fields=['asset', 'date'], name='content_dai_asset_i_efcf75_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyassetstats',
            index=models.Index(fields=['date', 'view_count'], name='content_dai_date_e2ce94_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyassetstats',
            index=models.Index(fields=['date', 'unique_viewers'], name='content_dai_date_53ccf1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyassetstats',
            unique_together={('asset', 'date')},
        ),
        migrations.AddIndex(
            model_name='assetview',
            index=models.Index(fields=['asset', 'viewed_at'], name='content_ass_asset_i_a00934_idx'),
        ),
        migrations.AddIndex(
            model_name='assetview',
            index=models.Index(fields=['user', 'viewed_at'], name='content_ass_user_id_3b2160_idx'),
        ),
        migrations.AddIndex(
            model_name='assetview',
            index=models.Index(fields=['session_id', 'asset'], name='content_ass_session_c89744_idx'),
        ),
        migrations.AddIndex(
            model_name='assetview',
            index=models.Index(fields=['viewed_at'], name='content_ass_viewed__637c6b_idx'),
        ),
    ]
