# Generated by Django 5.1 on 2025-12-01 08:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Brief description of the activity')),
                ('activity_number', models.PositiveIntegerField(help_text='Activity sequence number (1, 2, 3, etc.)')),
                ('grade', models.CharField(choices=[('K', 'Kindergarten'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8')], max_length=2)),
                ('topics', models.JSONField(default=list, help_text="Fraction topics covered (e.g., ['Mixed Denominators', 'Equivalent Fractions'])")),
                ('location', models.CharField(choices=[('classroom', 'Classroom'), ('court', 'Court'), ('both', 'Both')], default='classroom', help_text='Where the activity takes place', max_length=20)),
                ('prerequisites', models.JSONField(default=list, help_text='List of prerequisite skills/knowledge')),
                ('learning_objectives', models.TextField(blank=True, help_text='What students will learn')),
                ('materials', models.JSONField(default=list, help_text='Materials needed for the activity')),
                ('game_rules', models.JSONField(default=list, help_text='Step-by-step game rules')),
                ('key_terms', models.JSONField(default=dict, help_text='Key vocabulary terms and definitions')),
                ('icon_type', models.CharField(default='cone', help_text='Icon identifier for display (cone, bottle-cap, person, etc.)', max_length=50)),
                ('thumbnail_uri', models.URLField(blank=True, help_text='Optional custom thumbnail image')),
                ('is_published', models.BooleanField(default=True, help_text='Whether activity is visible')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within grade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_resources', models.ManyToManyField(blank=True, help_text='Resources for students', related_name='student_activities', to='content.resource')),
                ('teacher_resources', models.ManyToManyField(blank=True, help_text='Resources for teachers', related_name='teacher_activities', to='content.resource')),
                ('video_asset', models.ForeignKey(blank=True, help_text='Primary instructional video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='content.videoasset')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['grade', 'order', 'activity_number'],
                'indexes': [models.Index(fields=['grade', 'is_published'], name='content_act_grade_ecd7c4_idx'), models.Index(fields=['slug'], name='content_act_slug_aec683_idx'), models.Index(fields=['is_published', 'order'], name='content_act_is_publ_1cdeb7_idx')],
            },
        ),
    ]
